version: '3.3'

networks:
  questionnaire:
    driver: bridge

volumes:
  mysql:
    driver: local

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend/:/var/www/
      - ./dockerfiles/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - questionnaire

  backend:
    build:
      context: ./backend
      dockerfile: ../dockerfiles/backend/dockerfile
    container_name: backend
    volumes:
      - ./backend/:/var/www/
    networks:
      - questionnaire

  mysql:
    build:
      context: .
      dockerfile: ./dockerfiles/mysql/dockerfile
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'car_sharing'
      MYSQL_PASSWORD: 'root'
    networks:
      - questionnaire
    volumes:
      - ./dockerfiles/mysql/dump/:/var/lib/mysql/

  frontend:
    build:
      context: ./frontend
      dockerfile: ../dockerfiles/frontend/dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/var/www/
    #      - /var/www/node_modules
    networks:
      - questionnaire